"use strict";

const $ = (id) => document.getElementById(id);
const state = { logo: "", last: null };

// --- Go runtime -----------------------------------------------------------

const ready = new Promise((resolve) => window.addEventListener("goqr-ready", resolve, { once: true }));
(async () => {
  const go = new Go();
  const result = await WebAssembly.instantiateStreaming(fetch("qr.wasm"), go.importObject);
  go.run(result.instance);
})().catch((err) => {
  $("loading").textContent = "Could not load the WebAssembly module: " + err;
});

// --- Create ---------------------------------------------------------------

const presets = {
  classic: { moduleShape: "square", finderShape: "square", fg: "#000000", bg: "#ffffff", useGradient: false, useFinderColor: false },
  dots: { moduleShape: "dot", finderShape: "circle", fg: "#000000", bg: "#ffffff", useGradient: false, useFinderColor: false },
  rounded: { moduleShape: "rounded", finderShape: "rounded", fg: "#1c2026", bg: "#ffffff", useGradient: false, useFinderColor: false },
  gradient: { moduleShape: "rounded", finderShape: "rounded", bg: "#ffffff", useGradient: true, gradFrom: "#1a237e", gradTo: "#00695c", gradAngle: 45, useFinderColor: false },
  brand: { moduleShape: "dot", finderShape: "rounded", bg: "#ffffff", useGradient: true, gradFrom: "#4a148c", gradTo: "#c62828", gradAngle: 90, useFinderColor: true, finderRing: "#4a148c", finderCenter: "#c62828" },
};

function applyPreset(name) {
  for (const [key, value] of Object.entries(presets[name])) {
    const el = $(key);
    if (el.type === "checkbox") el.checked = value;
    else el.value = value;
  }
  $("transparent").checked = false;
  document.querySelectorAll("#presets button").forEach((b) => b.classList.toggle("active", b.dataset.preset === name));
  render();
}

function request() {
  const req = {
    text: $("text").value,
    ecc: $("ecc").value,
    simple: $("simple").checked,
    utf8eci: $("utf8eci").checked,
    moduleShape: $("moduleShape").value,
    finderShape: $("finderShape").value,
    fg: $("fg").value,
    bg: $("transparent").checked ? "#ffffff00" : $("bg").value,
    quietZone: +$("quietZone").value,
    scale: 10,
  };
  if ($("useGradient").checked) req.gradient = { from: $("gradFrom").value, to: $("gradTo").value, angle: +$("gradAngle").value };
  if ($("useFinderColor").checked) {
    req.finderRing = $("finderRing").value;
    req.finderCenter = $("finderCenter").value;
  }
  if (state.logo) {
    req.logo = state.logo;
    req.logoRatio = +$("logoRatio").value;
  }
  return req;
}

let pending = 0;
function render() {
  cancelAnimationFrame(pending);
  pending = requestAnimationFrame(async () => {
    await ready;
    syncControls();
    const req = request();
    const resp = JSON.parse(goqrEncode(JSON.stringify(req)));
    state.last = resp.error ? null : resp;
    $("dlPng").disabled = $("dlSvg").disabled = $("readCreated").disabled = !state.last;
    $("goCode").textContent = goCode(req);

    if (resp.error) {
      $("qr").innerHTML = "";
      const p = document.createElement("p");
      p.className = "err";
      p.textContent = resp.error;
      $("qr").append(p);
      setStatus("status", "", "");
      $("meta").replaceChildren();
      return;
    }
    $("qr").innerHTML = resp.svg; // generated by go-qr from validated options
    if (resp.verify) setStatus("status", "bad", "Not reliably readable: " + resp.verify);
    else setStatus("status", "ok", "✓ Verified: rendered, decoded and compared by Code.Verify");
    setMeta("meta", [
      ["Version", `${resp.version} (${resp.size}×${resp.size} modules)`],
      ["Error correction", resp.ecc + (resp.ecc !== req.ecc ? ` (raised from ${req.ecc})` : "")],
      ["Mask", resp.mask],
      ["Segments", (resp.segments || []).map((s) => `${s.mode} ${s.chars}`).join(", ") || "none"],
    ]);
  });
}

function syncControls() {
  document.querySelectorAll("fieldset .row[data-for]").forEach((row) => row.classList.toggle("off", !$(row.dataset.for).checked));
  $("fg").disabled = $("useGradient").checked;
  $("bg").disabled = $("transparent").checked;
  $("angleOut").textContent = $("gradAngle").value + "°";
  $("ratioOut").textContent = (+$("logoRatio").value).toFixed(2);
}

function goCode(req) {
  const hex = (h) => {
    const n = h.replace("#", "");
    const [r, g, b, a] = [0, 2, 4, 6].map((i) => (n.length > i ? n.slice(i, i + 2) : "ff"));
    return `color.RGBA{R: 0x${r}, G: 0x${g}, B: 0x${b}, A: 0x${a}}`;
  };
  const enc = [`qr.WithECC(qr.ECC${{ L: "Low", M: "Medium", Q: "Quartile", H: "High" }[req.ecc]})`];
  if (req.simple) enc.push("qr.WithSimpleSegmentation()");
  if (req.utf8eci) enc.push("qr.WithUTF8ECI()");
  const opts = [];
  if (req.quietZone !== 4) opts.push(`qr.WithQuietZone(${req.quietZone})`);
  const shape = { square: "Square", dot: "Dot", rounded: "Rounded", circle: "Circle" };
  if (req.moduleShape !== "square") opts.push(`qr.WithModuleShape(qr.Module${shape[req.moduleShape]})`);
  if (req.finderShape !== "square") opts.push(`qr.WithFinderShape(qr.Finder${shape[req.finderShape]})`);
  if (req.gradient) opts.push(`qr.WithGradient(${hex(req.gradient.from)}, ${hex(req.gradient.to)}, ${req.gradient.angle})`);
  else if (req.fg !== "#000000") opts.push(`qr.WithForeground(${hex(req.fg)})`);
  if (req.bg !== "#ffffff") opts.push(`qr.WithBackground(${req.bg === "#ffffff00" ? "color.Transparent" : hex(req.bg)})`);
  if (req.finderRing) opts.push(`qr.WithFinderColor(${hex(req.finderRing)}, ${hex(req.finderCenter)})`);
  if (req.logo) opts.push(`qr.WithLogo(logo, ${req.logoRatio})`);
  const list = opts.length ? "\n\t" + opts.join(",\n\t") + ",\n" : "";
  return `code, err := qr.Encode(${JSON.stringify(req.text)}, ${enc.join(", ")})
if err != nil {
	return err
}
opts := []qr.RenderOption{${list}}
if err := code.Verify(opts...); err != nil {
	return err // not safe to publish
}
png, err := code.PNG(opts...)`;
}

function download(name, href) {
  const a = document.createElement("a");
  a.href = href;
  a.download = name;
  a.click();
}

$("form").addEventListener("input", render);
$("presets").addEventListener("click", (e) => e.target.dataset.preset && applyPreset(e.target.dataset.preset));
$("logo").addEventListener("change", () => {
  const file = $("logo").files[0];
  if (!file) return;
  const reader = new FileReader();
  reader.onload = () => {
    state.logo = reader.result;
    if ($("ecc").value !== "H") $("ecc").value = "H";
    render();
  };
  reader.readAsDataURL(file);
});
$("clearLogo").addEventListener("click", () => {
  state.logo = "";
  $("logo").value = "";
  render();
});
$("dlPng").addEventListener("click", () => state.last && download("qr.png", state.last.png));
$("dlSvg").addEventListener("click", () => {
  if (!state.last) return;
  const url = URL.createObjectURL(new Blob([state.last.svg], { type: "image/svg+xml" }));
  download("qr.svg", url);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
});

// --- Read -----------------------------------------------------------------

const MAX_SIDE = 1000; // larger images are scaled down before decoding

function decodeSource(source, width, height) {
  const scale = Math.min(1, MAX_SIDE / Math.max(width, height));
  const canvas = $("canvas");
  canvas.width = Math.round(width * scale);
  canvas.height = Math.round(height * scale);
  const ctx = canvas.getContext("2d", { willReadFrequently: true });
  ctx.fillStyle = "#fff"; // transparent pixels read as light
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  ctx.drawImage(source, 0, 0, canvas.width, canvas.height);
  const data = ctx.getImageData(0, 0, canvas.width, canvas.height);
  const started = performance.now();
  const resp = JSON.parse(goqrDecode(data.data, data.width, data.height));
  resp.ms = performance.now() - started;
  return resp;
}

function showDecoded(resp) {
  if (resp.error) {
    setStatus("decodeStatus", "bad", "No code read: " + resp.error);
    $("decoded").hidden = true;
    $("decodeMeta").replaceChildren();
    return;
  }
  setStatus("decodeStatus", "ok", `✓ Decoded in ${resp.ms.toFixed(0)} ms`);
  $("decoded").hidden = false;
  $("decoded").textContent = resp.text;
  setMeta("decodeMeta", [
    ["Version", resp.version],
    ["Error correction", resp.ecc],
    ["Mask", resp.mask],
    ["Segments", (resp.segments || []).map((s) => `${s.mode} ${s.chars}`).join(", ")],
    ["Payload", resp.payload || "plain text"],
    ...(resp.mirrored ? [["Mirrored", "yes"]] : []),
    ...(resp.gs1 ? [["GS1", "yes"]] : []),
  ]);
}

async function decodeFile(file) {
  await ready;
  stopCamera();
  const img = new Image();
  img.onload = () => {
    showDecoded(decodeSource(img, img.naturalWidth, img.naturalHeight));
    URL.revokeObjectURL(img.src);
  };
  img.onerror = () => setStatus("decodeStatus", "bad", "That file is not an image the browser can open.");
  img.src = URL.createObjectURL(file);
}

const drop = $("drop");
$("file").addEventListener("change", () => $("file").files[0] && decodeFile($("file").files[0]));
["dragenter", "dragover"].forEach((t) => drop.addEventListener(t, (e) => { e.preventDefault(); drop.classList.add("over"); }));
["dragleave", "drop"].forEach((t) => drop.addEventListener(t, () => drop.classList.remove("over")));
drop.addEventListener("drop", (e) => {
  e.preventDefault();
  if (e.dataTransfer.files[0]) decodeFile(e.dataTransfer.files[0]);
});
$("readCreated").addEventListener("click", () => {
  if (!state.last) return;
  decodeFile(dataURLToBlob(state.last.png));
});

function dataURLToBlob(url) {
  const bin = atob(url.split(",")[1]);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return new Blob([bytes], { type: "image/png" });
}

let stream = null;
let scanTimer = 0;

async function startCamera() {
  await ready;
  try {
    stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" } });
  } catch (err) {
    setStatus("decodeStatus", "bad", "Camera unavailable: " + err.message);
    return;
  }
  const video = $("video");
  video.srcObject = stream;
  video.hidden = false;
  await video.play();
  $("camera").textContent = "Stop camera";
  setStatus("decodeStatus", "", "");
  const scan = () => {
    if (!stream) return;
    if (video.videoWidth) {
      const resp = decodeSource(video, video.videoWidth, video.videoHeight);
      if (!resp.error) {
        showDecoded(resp);
        stopCamera();
        return;
      }
    }
    scanTimer = setTimeout(scan, 200);
  };
  scan();
}

function stopCamera() {
  clearTimeout(scanTimer);
  if (stream) stream.getTracks().forEach((t) => t.stop());
  stream = null;
  $("video").hidden = true;
  $("camera").textContent = "Use camera";
}

$("camera").addEventListener("click", () => (stream ? stopCamera() : startCamera()));

// --- Helpers --------------------------------------------------------------

function setStatus(id, kind, text) {
  const el = $(id);
  el.className = "status " + kind;
  el.textContent = text;
}

function setMeta(id, rows) {
  $(id).replaceChildren(...rows.flatMap(([k, v]) => {
    const dt = document.createElement("dt");
    const dd = document.createElement("dd");
    dt.textContent = k;
    dd.textContent = v;
    return [dt, dd];
  }));
}

// ?text=...&preset=... prefills the form, so a style can be shared as a link.
ready.then(() => {
  $("loading").classList.add("done");
  const params = new URLSearchParams(location.search);
  if (params.has("text")) $("text").value = params.get("text");
  if (presets[params.get("preset")]) applyPreset(params.get("preset"));
  else render();
});
