# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.18.0'
      - run: go version

#      - name: Build
#        run: go build -v ./...

      - name: Test
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic
      - name: Vet
        run: go vet ./...
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"